version: '3.8'
services:
  app:
    environment:
      DB_HOST: 10.100.0.3
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    networks:
      musicNetwork:
        ipv4_address: 10.100.0.2
    ports:
      - '8080:8080'
    expose:
      - "8080"
#    network_mode: "host"
    depends_on:
      - 'db'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      musicNetwork:
        ipv4_address: 10.100.0.3
volumes:
  db:
    driver: local
networks:
  musicNetwork:
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.1/16