spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    changelog: classpath:db/changelog.yml
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    emcoding: utf-8
    suffix: .html
    mode: HTML5
    prefix: classpath:/templates/
  mvc:
    hiddenmethod:
      filter:
        enabled: true